name: transport_logistics
description: Transport & Logistics starter
publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  cloud_firestore: ^4.0.0
  firebase_auth: ^4.0.0
  provider: ^6.0.0
  flutter_dotenv: ^6.0.0
  # add google_maps_flutter or flutter_map when ready
